BookStoreWebApp/BookStoreWebApp/Controllers/BookController.cs
using BookStore.Models;
using BookStore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;

namespace BookStoreWepApp.Controllers
{
    public class BookController : Controller
    {
        // GET: 
        public ActionResult Index()
        {
            return View();
        }



        // GET: 
        public ActionResult BookDetails(int id)
        {
            var book = BasicFunctions.GetBookWithDetailsById(id);
            return View(book);
        }



        // GET: 
        public ActionResult Create()
        {
            ViewBag.GenreId =
                new SelectList
                (
                    AdvancedRepositoryFunctions.GetAll<Genre>(),
                    "GenreId",
                    "GenreType"
            );
            ViewBag.AuthorId =
                   new SelectList
                    (
                        AdvancedRepositoryFunctions.GetAll<Author>(),
                        "AuthorId",
                        "FullName"
                    );

            return View();
        }



        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {
            try
            {
                AdvancedRepositoryFunctions.Create<Book>(book);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }








   
        // (Navigates to Edit Page)
        public ActionResult EditBook(int id)
        {
            var book = AdvancedRepositoryFunctions.GetById<Book>(id);

            ViewBag.GenreId =
                new SelectList
                (
                    AdvancedRepositoryFunctions.GetAll<Genre>(),
                    "GenreId",
                    "GenreType"
            );
            ViewBag.AuthorId =
                   new SelectList
                    (
                        AdvancedRepositoryFunctions.GetAll<Author>(),
                        "AuthorId",
                        "FullName"
                    );

            return View(book);
        }


 
        // (Updates the Book)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBook(int id, IFormCollection collection)
        {
            try
            {
                var targetGenre =
                    AdvancedRepositoryFunctions
                        .GetById<Genre>
                        (
                            int.Parse(collection["GenreId"])
                        );

                var targetAuthor =
                    AdvancedRepositoryFunctions
                        .GetById<Author>
                        (
                            int.Parse(collection["AuthorId"])
                        );

                var propsToUpdate = new List<(string propName, object? propValue)>
                {
                    (nameof(Book.BookTitle), (string)collection[nameof(Book.BookTitle)]),
                    (nameof(Book.YearOfRelease), short.Parse(collection[nameof(Book.YearOfRelease)])),
                    (nameof(Book.Genre), targetGenre),
                    (nameof(Book.Author), targetAuthor)
                };


                AdvancedRepositoryFunctions
                    .Update<Book>
                    (
                        id,
                        propsToUpdate
                    );

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }


        // GET: 
        public ActionResult Delete(int id)
        {
            var book = BasicFunctions.GetBookWithDetailsById(id);
            return View(book);
        }


        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                AdvancedRepositoryFunctions.Delete<Book>(id);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStoreWebApp/BookStoreWebApp/Controllers/HomeController.cs
using BookStore;
using BookStoreWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookStoreWepApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var books = BasicFunctions.GetAllBooksWithDetails();
            return View(books);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookStoreWebApp/BookStoreWebApp/Views/Home/Index.cshtml
@model IEnumerable<BookStore.Models.Book>

@{
    ViewData["Title"] = "Books";
}

<h1>Book List</h1>

<p>
    <a asp-controller="Book" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearOfRelease)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfRelease)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.AuthorLast), @Html.DisplayFor(modelItem => item.Author.AuthorFirst)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre.GenreType)
                </td>
                <td>
                    <a asp-controller="Book" asp-action="EditBook" asp-route-id="@item.BookId">Edit</a> |
                    <a asp-controller="Book" asp-action="BookDetails" asp-route-id="@item.BookId">Details</a> |
                    <a asp-controller="Book" asp-action="Delete" asp-route-id="@item.BookId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>